name: icapeg Setup and Run

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Also trigger on pull requests to the main branch

jobs:
  build_and_run:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Or specify the Go version you need

      - name: Install icapeg dependencies (if any)
        run: |
          go get -v -t -d ./... 

      - name: Build icapeg
        run: go build .

      - name: Run icapeg
        run: ./icapeg 
